version: '3.7'
services:

  redis:
    image: redis
    ports:
    - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mongo:
    image: webhippie/mongodb:latest
    container_name: ${NAMESPACE}-mongodb
    restart: always
    ports:
    - 27017:27017
    - 28017:28017
    - 27019:27019
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    networks:
    - internal
    environment:
    - MONGODB_AUTH=${MONGODB_AUTH}
    - MONGODB_AUTH_DB=${MONGODB_AUTH_DB}
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_DBPATH=${MONGODB_DBPATH}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    - MONGODB_REST=${MONGODB_REST}
    - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
    - MONGODB_USERNAME=${MONGODB_USERNAME}
    - MONGODB_VERBOSE=${MONGODB_VERBOSE}

  mongoexpress:
    restart: always
    image: mongo-express
    container_name: ${NAMESPACE}-mongoexpress
    links:
    - mongo:mongo
    environment:
    - VCAP_APP_PORT=8090
    - ME_CONFIG_MONGODB_AUTH_USERNAME=""
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=""
    depends_on:
    - mongo
    ports:
    - 8090:8090
    networks:
    - internal
    - web

  tor:
    restart: always
    container_name: ${NAMESPACE}-tor-haproxy
    image: x0rzkov/tor-haproxy:latest
    build:
      context: .docker/tor-haproxy
      dockerfile: Dockerfile
    environment:
    - privoxy=1
    - privoxy_port=8119
    - tors=75
    networks:
    - internal
    - web
    ports:
    - 5566:5566
    - 2090:2090
    - 8119:8119

  spider:
    image: tor-spider
    depends_on:
    #  - tor
      - redis
      - elasticsearch
      - mongo
    ports:
    - 8888:8888
    environment:
    - REDIS_URI=${REDIS_URI}
    - ELASTIC_URI=${ELASTIC_URI}
    - ELASTIC_INDEX=${ELASTIC_INDEX}
    - PROXY_URI=${PROXY_URI}
    - MONGO_URI=${MONGO_URI}
    - MONGO_DB=${MONGO_DB}
    - MONGO_COL=${MONGO_COL}

volumes:
  mongo-data:
  mongo-backup:

networks:
  internal:
  web:
    external: true
